### ISSUE TITLE
It will break in MACOS because grep by default is BSD not GNU in MACOS

### ISSUE THREAD

**Issue by prayas1337** [baibhavanand/fbuid#8]
./fbid.sh 

		  _         ___  _  
		 |_ |_  | |  |  | \ 
		 |  |_) |_| _|_ |_/ 
					                    

 
   -Extract UserIDs From Public Facebook Accounts-
      
---Made With Love By - Baibhav | Twitter : @spongebhav---

Enter Username: zuck

usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Facebook is probably blocking our request. Please try again later.

We can add check for this in code.

**Comment by prayas1337** [comment]
Created PR commit c994cdeaf3fb6b60a9cac257e15c8305fa444b3f

**Comment by baibhavanand** [comment]
Thanks for solving the issue.
